name: input-demo1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'choose the input option'
        required: true
        default: 'dev'
        options:
          - dev
          - build
          - test
        type: choice

      artifact-tag:
        description: enter the value of artifact tag
        required: true
        type: string

jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy an APP
        run: echo "Deploying an artifact to ${{ inputs.artifact-tag}} yo application ${{ inputs.environment }}"
