name: Pushevent
on :
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  srcfilename:
    runs-on: ubuntu-latest
    steps:
      - name: source file change
        run: echo "code change only in source folder"