name: Branch Filter Learning Workflow

# पहले हम सिर्फ 'on: push' लिखते थे, अब हम इसे कंट्रोल करेंगे
on:
  push:
    branches:
      - main     # इसका मतलब है: यह वर्कफ़्लो सिर्फ और सिर्फ 'main' ब्रांच पर पुश होने पर चलेगा।

jobs:
  production-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: |
          echo "यह मैसेज आपको तभी दिखेगा जब कोड 'main' ब्रांच पर पुश हुआ होगा!"
          echo "कोड पुश करने वाले का नाम है: ${{ github.actor }}"
